#ifndef TYPECODE_H
#define TYPECODE_H
//Define all tokens code

enum Symbols {
    IDEN,CONSTTK,INTCON,REALCON,CHARCON,STRCON,VARTK,INTTK,FLOATTK,CHARTK,ARRAYTK,OFTK,REPTTK,UNLTK,IFTK,THENTK,ELSETK,DOTK,WHILETK,SWITCHTK,CASETK,FORTK,TOTK,
    BYTK,DOWNTOTK,PROCETK,FUNCTK,READTK,WRITETK,CALLTK,BEGINTK,ENDTK,ODDTK,PLUS,MINU,MULT,DIV,LSS,LEQ,GRE,GEQ,EQL,NEQ,ASSIGN,SEMICN,COMMA,PERIOD,COLON,QMARK,
    DQMARK,LPARENT,RPARENT,LBRACK,RBRACK,LBRACE,RBRACE,EXACTONCE,ZEROORONE,ZEROORINF,ERRORSYM
};

#endif